function driverNav() {
document.write('<ul id="nav"><li style="width: 124px;"><a class="main" style="border-right: 0;">&nbsp;</a></li><li style="width:56px;"><a class="main" href="/skydoc/index.html" target="_self">Home</a></li><li><a class="main" href="/skydoc/skyway_availability.html" target="_self">SkyWay Availability</a><ul><li><a href="/skydoc/dealer_locator.html" target="_self">Find a SkyWay Dealer</a></li></ul></li><li><a class="main" href="/skydoc/features.html" target="_self">Features &amp; Benefits</a><ul><li><a href="/skydoc/skyway_technology.html" target="_self">SkyWay Technology</a></li><li><a href="/skydoc/video.html" target="_self">SkyWay Video</a></li></ul></li><li><a class="main" href="/skydoc/about_skyway.html" target="_self">Our Company</a><ul><li><a href="/skydoc/skyway_management.html" target="_self">Leadership</a></li><li><a href="/skydoc/strategic_partnerships.html" target="_self">Strategic Partnerships</a></li><li><a href="/skydoc/investor_relations.html" target="_self">Investor Relations</a></li><li><a href="/skydoc/news_and_media.html">Media Room</a></li><li><a href="/skydoc/employment.html" target="_self">Employment</a></li></ul></li><li><a class="main" href="/skydoc/contact_us.html" target="_self">Contact Us</a><ul><li><a href="/skydoc/become_subscriber.html" target="_self">Become a Subscriber</a></li><li><a href="/skydoc/become_dealer.html" target="_self">Become a SkyWay Dealer</a></li><li><a href="/skydoc/faq.html"target="_self">Frequently Asked Questions</a></li></ul></li></ul>');
}

function driverFooter() {
document.write('<div><span class="lf">&copy; 2008 SkyWay Systems Inc., All Rights Reserved</span></div><div><span class="rf"><a href="/skydoc/index.html" target="_self">SkyWay</a> <a href="/skydoc/pdf/publicTermsAndConditions.pdf" target="_blank">Terms of Use</a><a href="/skydoc/pdf/publicPrivacyPolicy.pdf" target="_blank">Privacy</a><a href="/skydoc/contact_us.html" target="_self">Contact Us</a></span></div><div style="clear:both;"></div>');
}


function dealerNav() {
document.write('<ul id="nav"><li style="width: 124px;"><a class="main" style="border-right: 0;">&nbsp;</a></li><li style="width:56px;"><a class="main" href="/skydoc/dlr_index.html">Home</a></li><li><a class="main" href="/skydoc/dlr_skyway_availability.html" target="_self">SkyWay Availability</a></li><li><a class="main" href="/skydoc/dlr_features.html" target="_self">Features & Benefits</a><ul><li><a href="/skydoc/dlr_skyway_technology.html" target="_self">SkyWay Technology</a></li><li><a href="/skydoc/dlr_video.html" target="_self">SkyWay Video</a></li></ul></li><li><a class="main" href="/skydoc/dlr_about_skyway.html" target="_self">Our Company</a><ul><li><a href="/skydoc/dlr_skyway_management.html" target="_self">Leadership</a></li><li><a href="/skydoc/dlr_strategic_partnerships.html" target="_self">Strategic Partnerships</a></li><li><a href="/skydoc/dlr_investor_relations.html" target="_self">Investor Relations</a></li><li><a href="/skydoc/dlr_news_and_media.html" target="_self">Media Room</a></li><li><a href="/skydoc/dlr_employment.html" target="_self">Employment</a></li></ul></li><li><a class="main" href="/skydoc/dlr_contact_us.html" target="_self">Contact Us</a><ul><li><a href="/skydoc/dlr_become_dealer.html" target="_self">Become a SkyWay Dealer</a></li><li><a href="/skydoc/dlr_faq.html" target="_self">Frequently Asked Questions</a></li></ul></li></ul>');
}

function dealerFooter() {
document.write('<div><span class="lf">&copy; 2008 SkyWay Systems Inc., All Rights Reserved</span></div><div><span class="rf"><a href="/skydoc/dlr_index.html" target="_self">SkyWay</a> <a href="/skydoc/pdf/publicTermsAndConditions.pdf" target="_blank">Terms of Use</a><a href="/skydoc/pdf/publicPrivacyPolicy.pdf" target="_blank">Privacy</a><a href="/skydoc/dlr_contact_us.html" target="_self">Contact Us</a></span></div><div style="clear:both;"></div>');
}

